name: "Hub Update"
description: "This does the logic of pulling in the latest version of a given language"
inputs:
  source:
    description: "The name of the source repo"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Add / Update Submodule"
      shell: bash
      run: |
        ls;
        echo "${{ inputs.source }}"
        echo "and now i'd do the magic"
