name: "Hub Update"
description: "This does the logic of pulling in the latest version of a given language"
inputs:
  source:
    description: "The name of the source repo"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Checkout hub repo"
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: "Initialize Submodules"
      shell: bash
      run: |
        git submodule init;
        git submodule update;

    - name: "Add / Update Submodule"
      shell: bash
      run: |
        ls -lah;

        SOURCE="${{ inputs.source }}";
        RULE_LANG="${SOURCE: -2}";
        SUBMODULE="translations/${RULE_LANG}";

        echo "Checking for ${RULE_LANG}";
        if [ -e "${SUBMODULE}" ]; then
          git submodule update --remote "${SUBMODULE}";
        else
          echo "Creating submodule...";
          git submodule add git@github.com:${SOURCE}.git "${SUBMODULE}";
        fi

        git push;
