name: "Hub Update"
description: "This does the logic of pulling in the latest version of a given language"
inputs:
  source:
    description: "The name of the source repo"
    required: true
  pat:
    description: "A Personal Access Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout hub repo"
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: "Initialize Submodules"
      shell: bash
      run: |
        git submodule init;
        git submodule update;

    - name: "Add / Update Submodule"
      shell: bash
      env:
        PAT: ${{ inputs.pat }}
        SOURCE: ${{ inputs.source }}
      run: |
        ls -lah;

        RULE_LANG="${SOURCE: -2}";
        SUBMODULE_PATH="translations/${RULE_LANG}";
        SUBMODULE_GIT_URL="https://x-access-token:${PAT}@github.com/${SOURCE}"


        echo "Checking for ${RULE_LANG}";
        if [ -e "${SUBMODULE}" ]; then
          git submodule update --remote "${SUBMODULE}";
        else
          echo "Creating submodule...";
          git submodule add "${SUBMODULE_GIT_URL}" "${SUBMODULE}";
        fi

        git push;
