name: "Hub Update"
description: "This does the logic of pulling in the latest version of a given language"
inputs:
  source:
    description: "The name of the source repo"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Add / Update Submodule"
      shell: bash
      run: |
        SOURCE="${{ inputs.source }}";
        RULE_LANG="${SOURCE:-2}";
        echo "Checking for ${RULE_LANG}";
        if [ -e "translations/${RULE_LANG}" ]; then
          echo "it exists!";
        else
          echo "it doesn't exist";
        done
