name: "Update Hub"
description: "This does the logic of pulling in the latest version of a given language"
inputs:
  source:
    description: "The name of the source repo"
    required: true
  author:
    description: "The author of the commit that triggered this."
    default: "unknown"
  commit:
    description: "The commit message that triggered this."
    default: "unknown"
  pat:
    description: "A Personal Access Token"
    required: true
  hub-repo:
    description: "The repo to trigger."
    required: true
    default: smellofair/rules-hub

runs:
  using: "composite"
  steps:
    - name: "Checkout hub repo"
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.hub-repo }}
        token: ${{ inputs.pat }}
        submodules: true

    - name: "Initialize Submodules"
      shell: bash
      run: |

        git config --global user.name "Smell-o-bot"
        git config --global user.email "smell-o-bot@j.diode.pw"

        git submodule init;
        git submodule update;

    - name: "Add / Update Submodule"
      shell: bash
      env:
        PAT: ${{ inputs.pat }}
        SOURCE: ${{ inputs.source }}
        AUTHOR: ${{ inputs.author }}
        COMMIT: ${{ inputs.commit }}
      run: |
        ls -lhR;

        RULE_LANG="${SOURCE: -2}";
        SUBMODULE_PATH="translations/${RULE_LANG}";
        SUBMODULE_GIT_URL="https://github.com/${SOURCE}.git";

        LOCAL_COMMIT="Triggered by: ${AUTHOR} - ${COMMIT}";

        echo "Checking for ${RULE_LANG}";
        if [ -e "${SUBMODULE_PATH}" ]; then
          echo "Updating submodule...";
          git submodule update --remote --checkout -f "${SUBMODULE_PATH}";
          git add "${SUBMODULE_PATH}";
          git commit -m "Updating ${RULE_LANG}: ${LOCAL_COMMIT}";
        else
          echo "Creating submodule...";
          git submodule add "${SUBMODULE_GIT_URL}" "${SUBMODULE_PATH}";
          git commit -m "Adding ${SOURCE}: ${LOCAL_COMMIT}";
        fi

        git push;
