name: "Build Hub"
description: "This will build the static website from the rules-hub repo."
inputs:
  pat:
    description: "An access token with the correct permissions"
    required: true
  hub-repo:
    description: "The repo to trigger."
    required: true
    default: smellofair/rules-hub
runs:
  using: "composite"
  steps:
    - name: "Checkout the Hub"
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.hub-repo }}
        token: ${{ inputs.pat }}
        submodules: true

    - name: "dummy step"
      shell: bash
      env:
        PAT: ${{ inputs.pat }}
      run: |
        printf "# this is a dummy step for now.\n"; >> ../status.md;
        printf "\n# pwd\n" >> ../status.md;
        printf "\`$(pwd)\`\n" >> ../status.md;
        printf "\n# tree\n" >> ../status.md;
        printf "\`\`\`\r\n$(tree)\r\n\`\`\`\n" >> ../status.md;
        printf "\n# most recent commit\n" >> ../status.md;
        printf "```\n" >> ../status.md;
        git log -1 HEAD >> ../status.md;
        printf "```\n" >> ../status.md;

        git checkout -b gh_pages;
        git pull origin gh_pages || printf "No branch on origin yet.";

        rm -rf ./*;

        mv ../status.md ./;

        git add .;

        git config user.name "Smell-o-bot";
        git config user.email "smell-o-bot@j.diode.pw";

        git commit -m "adding status file?";
        git push -f origin gh_pages;
