name: "Trigger Hub"
description: "This will trigger the Hub Repo to pull in the changes from this repo."
inputs:
  hub-repo:
    description: "The repo to trigger."
    required: true
    default: cephalofair/rules-hub
  target-action:
    description: "The name of the action to trigger."
    required: true
    default: hub-update
  pat:
    description: "An access token with the correct permissions"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Pull the Trigger"
      shell: bash
      env:
        REPO: ${{ inputs.hub-repo }}
        TARGET_ACTION: ${{ inputs.target-action }}
        PAT: ${{ inputs.pat }}
      run: |
        service="${{ github.event.inputs.target_service }}"
        version="${{ github.event.inputs.target_version }}"
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${PAT}" \
          https://api.github.com/repos/${REPO}/dispatches \
          -d "{\"event_type\": \"${TARGEG_ACTION}\", \"client_payload\": {\"source\": \"${{ github.repository }}\"}}"
